### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by cblberlin** [giacomogaglione/chef-gpt#4]
https://github.com/giacomogaglione/chef-gpt/blob/88af8574482a10b78916a7a091061d26d336c9da/components/layout/site-header.tsx#L5

i'm trying something like this as well, but i get this error:
Cannot find module '@clerk/nextjs/dist/types/server' or its corresponding type declarations

even i downgraded into your clerk version 4.21.15 still the same

**Comment by giacomogaglione** [comment]
Have you tried restart the typescript server?

**Comment by cblberlin** [comment]
yes, a lot of times but still got the same result

> Have you tried restart the typescript server?

**Comment by cblberlin** [comment]
i think i will use useUser component from clerk to retrieve the information but it's just confusing to me why it won't work, i tried git clone your repository it works all fine but it just didn't work for me

**Comment by cblberlin** [comment]
ok, i figured out how to resolved the problem, the problem is on the tsconfig.json file, but i don't know which configuration trigger the import error, but anyway if someone encounter the same error as i did, here is the solution, take a look on **tsconfig.json** file, if it's auto-generate by create next app command might possibly get the same thing
```
// my tsconfig.json file
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}

// chef-gpt version:
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    },
    "plugins": [
      {
        "name": "next"
      }
    ],
    "strictNullChecks": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by cblberlin** [comment]
## Issue Description:

- With the TypeScript version used in this project (after compiling in the terminal), a warning is displayed:Warning: 

> Only plain objects can be passed to Client Components from Server Components. Classes or other objects with methods are not supported.

- However, in my environment using TypeScript version 5, this warning turns into a compilation error.

## Temporary Solution:

For those looking to circumvent this error, particularly when passing the User type from @clerk/nextjs, here's a workaround:

1. Ensure the User type is correctly imported by modifying the tsconfig.json file.
2. Temporarily downgrade TypeScript to version ^4.9.3 (the version I found to work without errors).

While I realize this solution isn't ideal, it does address the immediate compilation error, allowing us to proceed with other aspects of development.

## Seeking a More Elegant Solution:

I'm wondering if there's a more elegant or sustainable solution to this issue. Any insights or recommendations from the community would be greatly appreciated, especially if they can align with the latest TypeScript versions.Thank you for your attention to this matter.

**Comment by cblberlin** [comment]
well i used the latest version of typescript for now(5.3.3), it worked, it just throw some warning, but it can compile and run locally and pnpm run build throw no error as well, i guess i would just leave it that way

**Comment by giacomogaglione** [comment]
Thank you a lot for the effort <3
