### ISSUE TITLE
working in localhost but not working Clerk production

### ISSUE THREAD

**Issue by datacrud8** [giacomogaglione/chef-gpt#6]
Hi, Its nice project and like it. Thank you for sharing this.

I build this project in local with Clerk & working fine in localhost:3000 but when I want to deploy this to production so followed this url:
https://clerk.com/docs/deployments/overview
but non of the DNS urls are working. Already I have my existing domain name which was created in GoDaddy.com.

How to configure Clerk in production ? any help highly greatly appreciated!

**Comment by giacomogaglione** [comment]
Hi, sorry for the late reply.
I just followed Clerk guide for going to production

Have you replaced the clerk API keys with the production ones?

Edit:
I mark this as closed as it is not  a issue related to chef genie application
